version: '3.1'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - PORT=5433
      - DB_USER=postgres
      - DB_HOST=devops_postgres
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    container_name: devops_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azertyuiop
      PGDATA: /data/postgres
    restart: unless-stopped
    volumes:
      - postgres-persistent:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: devops_redis
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - nodejs
volumes:
  postgres-persistent:
    external: true
